<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kipp">
<!-- <xacro:include filename="$(find zed_wrapper)/urdf/zed_macro.urdf.xacro"/> -->

<!-- Robot constants-->

<xacro:property name="base_width" value= "0.5084"/>
<xacro:property name="base_height" value="0.51"/>
<xacro:property name="base_length" value="0.77975"/>

<xacro:property name="wheel_radius" value="0.0909"/>
<xacro:property name="wheel_width" value="0.1016"/>

<xacro:property name="footprint" value="${-((base_height/2)+(wheel_radius))}"/>

<xacro:property name="steering_xy" value="0.06155"/>
<xacro:property name="steering_z" value="0.23"/>


<xacro:property name="camera_x" value="0.34"/>
<xacro:property name="camera_z" value="${0.28+footprint}"/>

<xacro:property name="gnss_x" value="-0.21"/>
<xacro:property name="gnss_y" value="0.07"/>
<xacro:property name="gnss_z" value="${0.60+footprint}"/>
<xacro:property name="gnss_radius" value="0.03"/>
<xacro:property name="gnss_width" value="0.02"/>

<xacro:property name="imu_x" value="-0.21"/>
<xacro:property name="imu_y" value="0.07"/>
<xacro:property name="imu_z" value="${0.60+footprint}"/>
<xacro:property name="imu_radius" value="0.03"/>
<xacro:property name="imu_width" value="0.02"/> 

<xacro:property name="PI" value="3.1415692"/>
   
    <!-- Robot Base -->
   <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="rover_material">
                <color rgba="0.5 0.5 0.5 1.0" />
            </material>
        </visual>
    </link>


    <!-- Robot Footprint -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${footprint-wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- Steering --> 
    <xacro:macro name="steering" params="prefix x_reflect y_reflect">
        <link name="${prefix}_steering_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${steering_xy} ${steering_xy} ${steering_z}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_steering_link"/>
            <axis xyz="0 0 1"/>
            <origin xyz="${(x_reflect*base_length)/2} ${(y_reflect*base_width)/2} ${(footprint+wheel_radius)}" rpy="0 0 0"/>
            <limit lower="${-(PI/2)}" upper="${(PI/2)}" effort="0.0" velocity="0.0"/>
        </joint>
    </xacro:macro>

    <xacro:steering prefix="front_left" x_reflect="1" y_reflect="1"/>
    <xacro:steering prefix="front_right" x_reflect="1" y_reflect="-1"/>
    <xacro:steering prefix="back_left" x_reflect="-1" y_reflect="1"/>
    <xacro:steering prefix="back_right" x_reflect="-1" y_reflect="-1"/>


    <!-- Edge Wheels -->
    <xacro:macro name="edge_wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1.0"/>
                </material>
            </visual>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${(x_reflect*base_length)/2} ${(y_reflect*base_width)/2} ${footprint}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <xacro:edge_wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
    <xacro:edge_wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
    <xacro:edge_wheel prefix="back_left" x_reflect="-1" y_reflect="1"/>
    <xacro:edge_wheel prefix="back_right" x_reflect="-1" y_reflect="-1"/>

    <!-- Middle Left Wheel -->
    <link name="middle_left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="middle_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="middle_left_wheel_link"/>
        <origin xyz="0 ${(base_width)/2} ${footprint}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>


    <!-- Middle Right Wheel -->
    <link name="middle_right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="middle_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="middle_right_wheel_link"/>
        <origin xyz="0 ${-(base_width)/2} ${footprint}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>


    <!-- Sensors -->
    
  <link name="gnss_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${gnss_radius}" length="${gnss_width}"/>
            </geometry>
        </visual>
   </link>

    <joint name="gnss_joint" type="fixed">
        <parent link="base_link"/>
        <child link="gnss_link"/>
        <origin xyz="${gnss_x} ${gnss_y} ${gnss_z}" rpy="0 0 0"/>
    </joint>


    <link name="imu_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${imu_radius}" length="${imu_width}"/>
            </geometry>
        </visual>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
    </joint> 

</robot>