name: ROS 2 Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io
          sudo apt-get clean
          sudo apt-get autoclean
          sudo apt-get install -f
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Step 3: Build the Software_2025 workspace in a clean Docker container
      - name: Build Software_2025 workspace
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace osrf/ros:humble-desktop /bin/bash -c "source /opt/ros/humble/setup.bash && apt-get update && apt-get install -y python3-colcon-common-extensions && rm -rf build install log && colcon build --symlink-install"
