# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Arm_Group_controller

  Arm_Group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Shoulder Roll
      - Shoulder Pitch
      - Elbow Pitch
      - Elbow Roll
      - Wrist Pitch
      - Wrist Roll