# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Arm_Group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Arm_Group_controller:
  ros__parameters:
    joints:
      - Shoulder Roll
      - Shoulder Pitch
      - Elbow Pitch
      - Elbow Roll
      - Wrist Pitch
      - Wrist Roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity